### ISSUE TITLE
Links are loaded with ssl in localhost

### ISSUE THREAD

**Issue by dkapexhiu** [Fabio-Ottaviani-Dev/image-crud#1]
I am trying to run it in localhost without ssl. Only the homepage loads, the other links are with ssl (https). How to fix it in development server with http?

**Comment by Fabio-Ottaviani-Dev** [comment]
Hi, I develop it using: Homestead, 
I don't know what is your dev environment, I recommend to use: [Homestead](https://laravel.com/docs/5.7/homestead) or [Valet](https://laravel.com/docs/5.7/valet).
both of them design for Laravel.

**Comment by dkapexhiu** [comment]
Hello, i have set up homestead with laravel. It loads the app with https but it's a: DNS_PROBE_FINISHED_NXDOMAIN
I have followed your guide on github but it does not load the app.
Can you check the configuration on your server?

**Comment by Fabio-Ottaviani-Dev** [comment]
Hi, I don't know if you have set your local hosts
in osx: nano /etc/hosts
and add:
192.168.10.10	image-crud.test
(use your local ip)

in your .env file
APP_URL=http://image-crud.test

As you can see the url ending in .test unfortunatly the .dev
are banned in the modern browser like Crome whit the output of:
DNS_PROBE_FINISHED_NXDOMAIN
